import type { DocumentRecord, SourceAdapterStatus } from '@/lib/source-search/types';

export const SOURCE_ADAPTER_STATUSES: SourceAdapterStatus[] = [
  {
    adapter_id: 'ictihat-resmi-01',
    tab: 'ictihat',
    source_name: 'UYAP / Resmi Ictihat',
    mode: 'NOT_IMPLEMENTED_YET',
    verification_required: true,
    assumption: 'Resmi kaynakta kamuya acik API veya guvenli entegrasyon akisi olabilir.',
    validation_step: 'API dokumani, erisim izinleri ve kota sartlari teyit edilmelidir.',
    fallback_action: 'MVP asamasinda kullanici resmi arama sayfasina yonlendirilir.',
    fallback_url: 'https://www.turkiye.gov.tr/',
  },
  {
    adapter_id: 'ictihat-resmi-02',
    tab: 'ictihat',
    source_name: 'Yargitay Karar Arama',
    mode: 'REDIRECT_ONLY_MVP',
    verification_required: true,
    assumption: 'Direkt sorgu endpointi olmayabilir veya degisken olabilir.',
    validation_step: 'Resmi erisim yontemi dogrulanmadan sunucu tarafi cekim acilmayacak.',
    fallback_action: 'Arama terimi ile kaynak sayfasina yonlendirme.',
    fallback_url: 'https://karararama.yargitay.gov.tr/',
  },
  {
    adapter_id: 'mevzuat-resmi-01',
    tab: 'mevzuat',
    source_name: 'Mevzuat Bilgi Sistemi',
    mode: 'REDIRECT_ONLY_MVP',
    verification_required: true,
    assumption: 'Resmi API erisimi kurum bazli izin gerektirebilir.',
    validation_step: 'Kamuya acik endpoint, kimlik dogrulama ve kullanim kosullari dogrulanacak.',
    fallback_action: 'Maddeli arama terimiyle resmi mevzuat sayfasina yonlendirme.',
    fallback_url: 'https://www.mevzuat.gov.tr/',
  },
  {
    adapter_id: 'akademik-dergipark-oai',
    tab: 'akademik',
    source_name: 'DergiPark OAI-PMH',
    mode: 'NOT_IMPLEMENTED_YET',
    verification_required: true,
    assumption: 'OAI-PMH ile metadata hasadi yapilabilir.',
    validation_step: 'Set/spec, hasat limitleri ve metadata lisanslari netlestirilmeli.',
    fallback_action: 'MVPde sadece makale sayfasina yonlendirme ve metadata gosterimi.',
    fallback_url: 'https://dergipark.org.tr/',
  },
  {
    adapter_id: 'web-search-01',
    tab: 'web',
    source_name: 'Google Programmable Search',
    mode: 'NOT_IMPLEMENTED_YET',
    verification_required: true,
    assumption: 'Resmi API ile site kisitli arama yapilabilir.',
    validation_step: 'API anahtari, kota, fiyatlama ve alan adi kisitlari dogrulanacak.',
    fallback_action: 'MVPde sadece arama linkine yonlendirme (scraping yok).',
    fallback_url: 'https://www.google.com/',
  },
];

export const MOCK_DOCUMENTS: DocumentRecord[] = [
  {
    id: 'ictihat-001',
    source_type: 'ictihat',
    source_name: 'Yargitay',
    court: 'Yargitay',
    chamber: '3. Hukuk Dairesi',
    decision_date: '2022-11-18',
    publish_date: '2022-12-02',
    esas_no: '2021/3456',
    karar_no: '2022/7890',
    title: 'Kira uyarlama talebinde emsal sozlesme degeri',
    snippet: 'Uyarlama davasinda ekonomik dalgalanma ve emsal kira verileri birlikte degerlendirilmelidir.',
    full_text: null,
    authors: null,
    doi: null,
    tags: ['kira', 'uyarlama', 'borclar hukuku'],
    url_original: 'https://karararama.yargitay.gov.tr/',
    created_at: '2026-03-01T08:00:00.000Z',
    updated_at: '2026-03-01T08:00:00.000Z',
  },
  {
    id: 'ictihat-002',
    source_type: 'ictihat',
    source_name: 'Danistay',
    court: 'Danistay',
    chamber: '10. Daire',
    decision_date: '2021-05-06',
    publish_date: '2021-05-30',
    esas_no: '2020/1111',
    karar_no: '2021/2222',
    title: 'Idari para cezalarinda olcululuk denetimi',
    snippet: 'Olcululuk ilkesi, idari para cezasinin miktari ve etkisi acisindan somut olayda test edilir.',
    full_text: null,
    authors: null,
    doi: null,
    tags: ['idare hukuku', 'olcululuk', 'idari para cezasi'],
    url_original: 'https://www.danistay.gov.tr/',
    created_at: '2026-03-01T08:00:00.000Z',
    updated_at: '2026-03-01T08:00:00.000Z',
  },
  {
    id: 'ictihat-003',
    source_type: 'ictihat',
    source_name: 'AYM',
    court: 'Anayasa Mahkemesi',
    chamber: 'Genel Kurul',
    decision_date: '2020-10-14',
    publish_date: '2020-11-05',
    esas_no: '2018/99',
    karar_no: '2020/77',
    title: 'Adil yargilanma hakki ve makul sure incelemesi',
    snippet: 'Makul sure asimi iddiasi degerlendirilirken davanin karmasikligi ve taraf davranislari dikkate alinir.',
    full_text: null,
    authors: null,
    doi: null,
    tags: ['adil yargilanma', 'makul sure', 'anayasa'],
    url_original: 'https://kararlarbilgibankasi.anayasa.gov.tr/',
    created_at: '2026-03-01T08:00:00.000Z',
    updated_at: '2026-03-01T08:00:00.000Z',
  },
  {
    id: 'mevzuat-001',
    source_type: 'mevzuat',
    source_name: 'Mevzuat',
    court: null,
    chamber: null,
    decision_date: null,
    publish_date: '2011-02-04',
    esas_no: null,
    karar_no: null,
    title: '6098 sayili Turk Borclar Kanunu - Madde 138',
    snippet: 'Asiri ifa guclugu halinde sozlesmenin uyarlanmasi veya fesih talep edilmesi duzenlenir.',
    full_text: null,
    authors: null,
    doi: null,
    tags: ['tbk', 'madde 138', 'asiri ifa guclugu'],
    url_original: 'https://www.mevzuat.gov.tr/',
    created_at: '2026-03-01T08:00:00.000Z',
    updated_at: '2026-03-01T08:00:00.000Z',
  },
  {
    id: 'mevzuat-002',
    source_type: 'mevzuat',
    source_name: 'Resmi Gazete',
    court: null,
    chamber: null,
    decision_date: null,
    publish_date: '2011-02-04',
    esas_no: null,
    karar_no: null,
    title: '6100 sayili HMK - Delillerin degerlendirilmesi',
    snippet: 'Hakim, delilleri serbestce takdir eder ve gerekcesini kararda aciklar.',
    full_text: null,
    authors: null,
    doi: null,
    tags: ['hmk', 'delil', 'ispat'],
    url_original: 'https://www.resmigazete.gov.tr/',
    created_at: '2026-03-01T08:00:00.000Z',
    updated_at: '2026-03-01T08:00:00.000Z',
  },
  {
    id: 'mevzuat-003',
    source_type: 'mevzuat',
    source_name: 'Mevzuat',
    court: null,
    chamber: null,
    decision_date: null,
    publish_date: '2003-06-10',
    esas_no: null,
    karar_no: null,
    title: '4857 sayili Is Kanunu - Fazla calisma',
    snippet: 'Fazla calisma ucreti ve yillik sinirlar isverenin yukumlulugu kapsaminda duzenlenmistir.',
    full_text: null,
    authors: null,
    doi: null,
    tags: ['is hukuku', 'fazla mesai', 'ucret'],
    url_original: 'https://www.mevzuat.gov.tr/',
    created_at: '2026-03-01T08:00:00.000Z',
    updated_at: '2026-03-01T08:00:00.000Z',
  },
  {
    id: 'akademik-001',
    source_type: 'akademik',
    source_name: 'DergiPark',
    court: null,
    chamber: null,
    decision_date: null,
    publish_date: '2024-01-15',
    esas_no: null,
    karar_no: null,
    title: 'Sozlesme uyarlama davalarinda ekonomik indeks kullanimi',
    snippet: 'Calisma, kira uyarlama yargilamalarinda TUFE ve alternatif endekslerin etkisini tartisir.',
    full_text: null,
    authors: ['A. Yilmaz', 'B. Demir'],
    doi: '10.0000/mock.2024.001',
    tags: ['kira uyarlama', 'akademik', 'dergipark'],
    url_original: 'https://dergipark.org.tr/',
    created_at: '2026-03-01T08:00:00.000Z',
    updated_at: '2026-03-01T08:00:00.000Z',
  },
  {
    id: 'akademik-002',
    source_type: 'akademik',
    source_name: 'Universite Hukuk Dergisi',
    court: null,
    chamber: null,
    decision_date: null,
    publish_date: '2023-09-05',
    esas_no: null,
    karar_no: null,
    title: 'Idari para cezalarinda olcululuk testinin evrimi',
    snippet: 'Danistay ve AYM kararlarindan hareketle olcululuk testinin sinirlari ele alinmistir.',
    full_text: null,
    authors: ['C. Kaya'],
    doi: null,
    tags: ['idare hukuku', 'olcululuk', 'akademik'],
    url_original: 'https://example.edu.tr/hukuk-dergisi',
    created_at: '2026-03-01T08:00:00.000Z',
    updated_at: '2026-03-01T08:00:00.000Z',
  },
  {
    id: 'web-001',
    source_type: 'web',
    source_name: 'Adalet Bakanligi',
    court: null,
    chamber: null,
    decision_date: null,
    publish_date: '2025-10-20',
    esas_no: null,
    karar_no: null,
    title: 'UYAP ve e-Durusma hakkinda resmi bilgilendirme',
    snippet: 'Resmi duyuruda sistem erisimi, surum notlari ve duyuru takvimi paylasilmistir.',
    full_text: null,
    authors: null,
    doi: null,
    tags: ['adalet.gov.tr', 'duyuru', 'uyap'],
    url_original: 'https://www.adalet.gov.tr/',
    created_at: '2026-03-01T08:00:00.000Z',
    updated_at: '2026-03-01T08:00:00.000Z',
  },
  {
    id: 'web-002',
    source_type: 'web',
    source_name: 'Resmi Gazete Arsivi',
    court: null,
    chamber: null,
    decision_date: null,
    publish_date: '2024-07-01',
    esas_no: null,
    karar_no: null,
    title: 'Resmi Gazete arama arayuzu kullanim notlari',
    snippet: 'Yayin tarihi, sayi ve metin bazli arama filtreleri ile belgeye hizli ulasim anlatilmistir.',
    full_text: null,
    authors: null,
    doi: null,
    tags: ['gov.tr', 'resmi gazete', 'arsiv'],
    url_original: 'https://www.resmigazete.gov.tr/',
    created_at: '2026-03-01T08:00:00.000Z',
    updated_at: '2026-03-01T08:00:00.000Z',
  },
  {
    id: 'web-003',
    source_type: 'web',
    source_name: 'TBB',
    court: null,
    chamber: null,
    decision_date: null,
    publish_date: '2025-02-12',
    esas_no: null,
    karar_no: null,
    title: 'Barolar Birligi mesleki duyurular',
    snippet: 'Meslek icrasi ve avukatlik uygulamalarina dair guncel bilgilendirme metni.',
    full_text: null,
    authors: null,
    doi: null,
    tags: ['barobirlik', 'duyuru', 'avukatlik'],
    url_original: 'https://www.barobirlik.org.tr/',
    created_at: '2026-03-01T08:00:00.000Z',
    updated_at: '2026-03-01T08:00:00.000Z',
  },
];

